In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor
)
from sklearn.metrics import r2_score, mean_absolute_error, root_mean_squared_error
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
import tensorflow as tf
from sklearn.model_selection import GridSearchCV
import joblib

In [2]:
raw_df = pd.read_csv("./SolarPanelData.csv").drop(columns=['Unnamed: 0'])
df = raw_df.copy()
df.head()
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values("Date")

In [3]:
def get_season(date):
    m = date.month
    if m in [3, 4, 5]:
        return "Spring"
    elif m in [6, 7, 8]:
        return "Summer"
    elif m in [9, 10, 11]:
        return "Fall"
    else:
        return "Winter"

In [4]:
df['Season'] = df['Date'].apply(get_season).astype(str)

df['Month'] = df['Date'].dt.month
df['DayOfYear'] = df['Date'].dt.dayofyear

df['PressureBin'] = pd.qcut(df['Pressure'], q=5, duplicates='drop').astype(str)

In [5]:
X = df.drop(columns=['Date', 'Solar(PV)', 'Pressure'])
y = df['Solar(PV)']

In [6]:
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.1, random_state=42)

In [7]:
X_train['Solar_lag1'] = y_train.shift(1)
X_train['Solar_lag7'] = y_train.shift(7)

X_val['Solar_lag1'] = y_val.shift(1)
X_val['Solar_lag7'] = y_val.shift(7)

X_test['Solar_lag1'] = y_test.shift(1)
X_test['Solar_lag7'] = y_test.shift(7)

In [8]:
train_mask = X_train[['Solar_lag1','Solar_lag7']].notna().all(axis=1)

X_train = X_train[train_mask]
y_train = y_train[train_mask]

val_mask = X_val[['Solar_lag1','Solar_lag7']].notna().all(axis=1)

X_val = X_val[val_mask]
y_val = y_val[val_mask]

test_mask = X_test[['Solar_lag1','Solar_lag7']].notna().all(axis=1)

X_test = X_test[test_mask]
y_test = y_test[test_mask]

In [9]:
display(X_train.columns)
num_cols = [
'AvgTemperture', 'AverageDew(point via humidity)', 'Humidity', 'Wind',
'Month', 'DayOfYear', 'Solar_lag1', 'Solar_lag7'
]
cat_cols = ['Season', 'PressureBin']

Index(['AvgTemperture', 'AverageDew(point via humidity)', 'Humidity', 'Wind',
       'Season', 'Month', 'DayOfYear', 'PressureBin', 'Solar_lag1',
       'Solar_lag7'],
      dtype='object')

In [10]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
        ("num", StandardScaler(), num_cols)
    ]
)

In [33]:
results = []

models = {
    "DecisionTree": DecisionTreeRegressor(random_state=42),
    "RandomForest": RandomForestRegressor(random_state=42),
    "ExtraTrees": ExtraTreesRegressor(random_state=42),
    "GradientBoosting": GradientBoostingRegressor(random_state=42),
    "XGBoost": XGBRegressor(random_state=42)
}

for name, model in models.items():
    pipe = Pipeline([
        ("preprocess", preprocessor),
        ("model", model)
    ])

    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_val)

    results.append({
        "Model": name,
        "R2": r2_score(y_val, y_pred),
        "MAE": mean_absolute_error(y_val, y_pred),
        "RMSE": root_mean_squared_error(y_val, y_pred)
    })

results_df = pd.DataFrame(results).sort_values("RMSE")
results_df

              Model        R2       MAE      RMSE
4           XGBoost  0.873338  2.401595  2.776464
2        ExtraTrees  0.842164  2.486358  3.099351
1      RandomForest  0.827568  2.845353  3.239490
3  GradientBoosting  0.803804  2.787926  3.455518
0      DecisionTree  0.679604  3.298857  4.415823

In [ ]:
xgb = models['XGBoost']

pipeline = Pipeline(steps=[
    ("preprocess", preprocessor),
    ("model", xgb)
])

pipeline.fit(X_train, y_train)

ohe = pipeline.named_steps["preprocess"].named_transformers_["cat"]

ohe_features = list(ohe.get_feature_names_out(cat_cols))

all_features = ohe_features + num_cols

xgb = pipeline.named_steps["model"]
importances = xgb.get_booster().get_score(importance_type='gain')

rows = []
for f, imp in importances.items():
    idX = int(f[1:])
    rows.append((all_features[idX], imp))

fi = (
    pd.DataFrame(rows, columns=['Feature', 'Importance'])
    .sort_values(by='Importance', ascending=False)
)

display(fi)

y_pred = pipeline.predict(X_val)

print("R²:", r2_score(y_val, y_pred))
print("MAE:", mean_absolute_error(y_val, y_pred))
print("RMSE:", root_mean_squared_error(y_val, y_pred))

                                   Feature  Importance
2                            Season_Summer   54.016632
0                              Season_Fall   48.046082
8                            AvgTemperture   27.255764
9           AverageDew(point via humidity)    7.955474
4   PressureBin_(28.898999999999997, 29.1]    7.116208
10                                Humidity    3.574533
7                 PressureBin_(29.3, 29.6]    2.863962
11                                    Wind    1.385124
12                                   Month    1.156673
1                            Season_Spring    0.993100
5                 PressureBin_(29.1, 29.2]    0.749826
6                 PressureBin_(29.2, 29.3]    0.464991
3                            Season_Winter    0.072626

R²: 0.8733375485386466
MAE: 2.4015952452795832
RMSE: 2.776464009490229

In [12]:
class FFRegressor:
    def __init__(self, num_cols, cat_cols):
        self.num_cols = num_cols
        self.cat_cols = cat_cols

        self.inputs = {}
        self.encoded = []

    def build_preprocessing(self, X_train):
        """
        Builds preprocessing layers and adapts them on training data.
        """

        for col in self.num_cols:
            inp = tf.keras.Input(shape=(1,), name=col, dtype="float32")
            self.inputs[col] = inp

            normalizer = tf.keras.layers.Normalization(axis=None)
            normalizer.adapt(X_train[col].to_numpy().reshape(-1, 1))

            self.encoded.append(normalizer(inp))

        for col in self.cat_cols:
            inp = tf.keras.Input(shape=(1,), name=col, dtype="string")
            self.inputs[col] = inp

            lookup = tf.keras.layers.StringLookup(output_mode="binary")
            lookup.adapt(X_train[col].to_numpy().reshape(-1, 1))

            self.encoded.append(lookup(inp))

    def build_model(self):
        """
        Builds and returns the compiled Keras model.
        """

        all_features = tf.keras.layers.Concatenate()(self.encoded)

        X = tf.keras.layers.Dense(24, activation="relu")(all_features)
        outputs = tf.keras.layers.Dense(1, activation="relu")(X)

        model = tf.keras.Model(inputs=self.inputs, outputs=outputs)

        model.compile(
            optimizer="sgd",
            loss="mse",
            metrics=[tf.keras.metrics.RootMeanSquaredError()]
        )

        return model

In [13]:
X_train_ff = X_train.copy()
X_val_ff   = X_val.copy()

X_train_ff_dict = {
    col: X_train_ff[col].to_numpy()
    for col in num_cols + cat_cols
}

X_val_ff_dict = {
    col: X_val_ff[col].to_numpy()
    for col in num_cols + cat_cols
}

In [14]:
regressor = FFRegressor(num_cols, cat_cols)
regressor.build_preprocessing(X_train)
model = regressor.build_model()

checkpoint = tf.keras.callbacks.ModelCheckpoint(
    "models/best_ffr.keras",
    monitor="val_loss",
    save_best_only=True
)


history = model.fit(
    x=X_train_ff_dict,
    y=y_train,
    epochs=50,
    batch_size=3,
    validation_data=(X_val_ff_dict, y_val),
    callbacks=[checkpoint]
)

Epoch 1/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 103.6512 - root_mean_squared_error: 10.1809 - val_loss: 50.9136 - val_root_mean_squared_error: 7.1354
Epoch 2/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 66.7553 - root_mean_squared_error: 8.1704 - val_loss: 44.2663 - val_root_mean_squared_error: 6.6533
Epoch 3/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 60.0143 - root_mean_squared_error: 7.7469 - val_loss: 36.2552 - val_root_mean_squared_error: 6.0212
Epoch 4/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56.6331 - root_mean_squared_error: 7.5255 - val_loss: 35.1888 - val_root_mean_squared_error: 5.9320
Epoch 5/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 42.2681 - root_mean_squared_error: 6.5014 - val_loss: 26.6935 - val_root_mean_squared_error: 5.1666
Epoch 6/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 36.3881 - root_mean_squared_error: 6.0323 - val_loss: 35.3321 - val_root_mean_squared_error: 5.9441
Epoch 7/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 43.5988 - root_mean_squared_error: 6.6029 - val_loss: 61.5127 - val_root_mean_squared_error: 7.8430
Epoch 8/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 36.4626 - root_mean_squared_error: 6.0384 - val_loss: 62.8434 - val_root_mean_squared_error: 7.9274
Epoch 9/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 34.4670 - root_mean_squared_error: 5.8709 - val_loss: 31.2979 - val_root_mean_squared_error: 5.5944
Epoch 10/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 33.2739 - root_mean_squared_error: 5.7684 - val_loss: 67.4611 - val_root_mean_squared_error: 8.2135
Epoch 11/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29.6181 - root_mean_squared_error: 5.4423 - val_loss: 17.6579 - val_root_mean_squared_error: 4.2021
Epoch 12/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 29.5713 - root_mean_squared_error: 5.4379 - val_loss: 53.4831 - val_root_mean_squared_error: 7.3132
Epoch 13/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 28.3497 - root_mean_squared_error: 5.3244 - val_loss: 22.6858 - val_root_mean_squared_error: 4.7630
Epoch 14/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 25.9240 - root_mean_squared_error: 5.0916 - val_loss: 31.7845 - val_root_mean_squared_error: 5.6378
Epoch 15/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 25.1382 - root_mean_squared_error: 5.0138 - val_loss: 34.7440 - val_root_mean_squared_error: 5.8944
Epoch 16/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 23.1093 - root_mean_squared_error: 4.8072 - val_loss: 18.6685 - val_root_mean_squared_error: 4.3207
Epoch 17/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 25.4142 - root_mean_squared_error: 5.0413 - val_loss: 49.3273 - val_root_mean_squared_error: 7.0233
Epoch 18/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21.1260 - root_mean_squared_error: 4.5963 - val_loss: 35.1904 - val_root_mean_squared_error: 5.9321
Epoch 19/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 21.4424 - root_mean_squared_error: 4.6306 - val_loss: 34.5892 - val_root_mean_squared_error: 5.8813
Epoch 20/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 22.7187 - root_mean_squared_error: 4.7664 - val_loss: 33.7511 - val_root_mean_squared_error: 5.8096
Epoch 21/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19.6362 - root_mean_squared_error: 4.4313 - val_loss: 27.1223 - val_root_mean_squared_error: 5.2079
Epoch 22/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21.3075 - root_mean_squared_error: 4.6160 - val_loss: 18.9515 - val_root_mean_squared_error: 4.3533
Epoch 23/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21.4049 - root_mean_squared_error: 4.6265 - val_loss: 29.3905 - val_root_mean_squared_error: 5.4213
Epoch 24/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.1695 - root_mean_squared_error: 4.2626 - val_loss: 19.9333 - val_root_mean_squared_error: 4.4647
Epoch 25/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19.8366 - root_mean_squared_error: 4.4538 - val_loss: 26.2789 - val_root_mean_squared_error: 5.1263
Epoch 26/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.2405 - root_mean_squared_error: 4.1522 - val_loss: 20.4641 - val_root_mean_squared_error: 4.5237
Epoch 27/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19.3498 - root_mean_squared_error: 4.3988 - val_loss: 26.5919 - val_root_mean_squared_error: 5.1567
Epoch 28/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19.8330 - root_mean_squared_error: 4.4534 - val_loss: 37.4221 - val_root_mean_squared_error: 6.1174
Epoch 29/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.6282 - root_mean_squared_error: 4.3160 - val_loss: 38.6087 - val_root_mean_squared_error: 6.2136
Epoch 30/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.1984 - root_mean_squared_error: 4.2660 - val_loss: 29.0718 - val_root_mean_squared_error: 5.3918
Epoch 31/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.6886 - root_mean_squared_error: 4.3230 - val_loss: 21.1675 - val_root_mean_squared_error: 4.6008
Epoch 32/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.3447 - root_mean_squared_error: 4.2831 - val_loss: 40.5034 - val_root_mean_squared_error: 6.3642
Epoch 33/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.8322 - root_mean_squared_error: 4.2228 - val_loss: 17.9932 - val_root_mean_squared_error: 4.2418
Epoch 34/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.3202 - root_mean_squared_error: 4.2802 - val_loss: 22.0054 - val_root_mean_squared_error: 4.6910
Epoch 35/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.0122 - root_mean_squared_error: 4.1246 - val_loss: 14.5025 - val_root_mean_squared_error: 3.8082
Epoch 36/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19.2515 - root_mean_squared_error: 4.3877 - val_loss: 24.5864 - val_root_mean_squared_error: 4.9585
Epoch 37/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15.6436 - root_mean_squared_error: 3.9552 - val_loss: 20.9688 - val_root_mean_squared_error: 4.5792
Epoch 38/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.5972 - root_mean_squared_error: 4.3124 - val_loss: 16.0254 - val_root_mean_squared_error: 4.0032
Epoch 39/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16.8053 - root_mean_squared_error: 4.0994 - val_loss: 30.2490 - val_root_mean_squared_error: 5.4999
Epoch 40/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16.5964 - root_mean_squared_error: 4.0739 - val_loss: 18.8591 - val_root_mean_squared_error: 4.3427
Epoch 41/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15.9794 - root_mean_squared_error: 3.9974 - val_loss: 25.7602 - val_root_mean_squared_error: 5.0755
Epoch 42/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.3808 - root_mean_squared_error: 4.2873 - val_loss: 16.9363 - val_root_mean_squared_error: 4.1154
Epoch 43/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.2860 - root_mean_squared_error: 4.1576 - val_loss: 23.9318 - val_root_mean_squared_error: 4.8920
Epoch 44/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.2378 - root_mean_squared_error: 4.1518 - val_loss: 22.7227 - val_root_mean_squared_error: 4.7668
Epoch 45/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 16.2461 - root_mean_squared_error: 4.0306 - val_loss: 24.2425 - val_root_mean_squared_error: 4.9237
Epoch 46/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 16.3530 - root_mean_squared_error: 4.0439 - val_loss: 15.3495 - val_root_mean_squared_error: 3.9178
Epoch 47/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14.9892 - root_mean_squared_error: 3.8716 - val_loss: 23.1544 - val_root_mean_squared_error: 4.8119
Epoch 48/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15.7642 - root_mean_squared_error: 3.9704 - val_loss: 20.4076 - val_root_mean_squared_error: 4.5175
Epoch 49/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15.5672 - root_mean_squared_error: 3.9455 - val_loss: 17.3368 - val_root_mean_squared_error: 4.1637
Epoch 50/50
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15.2318 - root_mean_squared_error: 3.9028 - val_loss: 19.9764 - val_root_mean_squared_error: 4.4695

In [15]:
def make_sequence_1d(x, timesteps):
    x = x.to_numpy()
    return np.array([
        x[i:i+timesteps]
        for i in range(len(x) - timesteps)
    ])

In [16]:
X_train_seq_dict = {}
X_val_seq_dict = {}

for col in num_cols:
    seq = make_sequence_1d(X_train[col], 7).astype("float32")
    X_train_seq_dict[col] = tf.convert_to_tensor(seq[:, :, None], dtype=tf.float32)

    seq_val = make_sequence_1d(X_val[col], 7).astype("float32")
    X_val_seq_dict[col] = tf.convert_to_tensor(seq_val[:, :, None], dtype=tf.float32)

for col in cat_cols:
    seq = make_sequence_1d(X_train[col].astype(str), 7)
    
    X_train_seq_dict[col] = tf.convert_to_tensor(seq[:, :, None], dtype=tf.string)

    seq_val = make_sequence_1d(X_val[col].astype(str), 7)
    X_val_seq_dict[col] = tf.convert_to_tensor(seq_val[:, :, None], dtype=tf.string)

y_train_seq = tf.convert_to_tensor(y_train.to_numpy()[7:].astype("float32"))
y_val_seq = tf.convert_to_tensor(y_val.to_numpy()[7:].astype("float32"))

In [17]:

print(X_train_seq_dict['AvgTemperture'][0])
print(X_train_seq_dict['AvgTemperture'].shape)

tf.Tensor(
[[76.4]
 [65.5]
 [66.5]
 [80.6]
 [77.7]
 [97.5]
 [75.1]], shape=(7, 1), dtype=float32)
(308, 7, 1)

In [18]:
class RNNRegressor:
    def __init__(self, num_cols, cat_cols, timesteps=7):
        self.num_cols = num_cols
        self.cat_cols = cat_cols
        self.timesteps = timesteps

        self.num_normalizers = {}
        self.cat_encoders = {}

    def adapt_preprocessing(self, X_train):

        for col in self.num_cols:
            normalizer = tf.keras.layers.Normalization(axis=None)
            normalizer.adapt(X_train[col].to_numpy().reshape(-1,1))
            self.num_normalizers[col] = normalizer

        for col in self.cat_cols:
            lookup = tf.keras.layers.StringLookup(output_mode='binary')
            lookup.adapt(X_train[col].to_numpy().reshape(-1,1))
            self.cat_encoders[col] = lookup

    def build_model(self):
        inputs = {}
        encoded_steps = []

        for col in self.num_cols:
            inp = tf.keras.layers.Input((self.timesteps, 1), name=col, dtype='float32')
            inputs[col] = inp

            x = tf.keras.layers.TimeDistributed(self.num_normalizers[col])(inp)
            encoded_steps.append(x)

        for col in self.cat_cols:
            inp = tf.keras.layers.Input((self.timesteps, 1), name=col, dtype='string')
            inputs[col] = inp

            x = tf.keras.layers.TimeDistributed(self.cat_encoders[col])(inp)
            encoded_steps.append(x)

        x = tf.keras.layers.Concatenate(axis=-1)(encoded_steps)

        x = tf.keras.layers.LSTM(32, activation='tanh')(x)
        x = tf.keras.layers.Dropout(0.5)(x)
        outputs = tf.keras.layers.Dense(1, activation='relu')(x)

        model = tf.keras.Model(inputs=inputs, outputs=outputs)

        model.compile(
            optimizer='adamW',
            loss="mse",
            metrics=['root_mean_squared_error']
        )

        return model

In [19]:
rnn = RNNRegressor(num_cols, cat_cols, timesteps=7)

rnn.adapt_preprocessing(X_train)
model = rnn.build_model()

checkpoint = tf.keras.callbacks.ModelCheckpoint(
    "models/best_rnnr.keras",
    monitor="val_loss",
    save_best_only=True
)

history = model.fit(
    x=X_train_seq_dict,
    y=y_train_seq,
    epochs=50,
    batch_size=3,
    validation_data=(X_val_seq_dict, y_val_seq),
    callbacks=[checkpoint]
)

Epoch 1/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 537.7645 - root_mean_squared_error: 23.1897 - val_loss: 323.1336 - val_root_mean_squared_error: 17.9759
Epoch 2/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 242.4734 - root_mean_squared_error: 15.5716 - val_loss: 203.6218 - val_root_mean_squared_error: 14.2696
Epoch 3/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 164.0760 - root_mean_squared_error: 12.8092 - val_loss: 149.3327 - val_root_mean_squared_error: 12.2202
Epoch 4/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 127.3249 - root_mean_squared_error: 11.2838 - val_loss: 118.2303 - val_root_mean_squared_error: 10.8734
Epoch 5/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 105.7391 - root_mean_squared_error: 10.2830 - val_loss: 97.4128 - val_root_mean_squared_error: 9.8698
Epoch 6/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 92.2506 - root_mean_squared_error: 9.6047 - val_loss: 86.2233 - val_root_mean_squared_error: 9.2857
Epoch 7/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 83.6569 - root_mean_squared_error: 9.1464 - val_loss: 79.1085 - val_root_mean_squared_error: 8.8943
Epoch 8/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 81.5022 - root_mean_squared_error: 9.0279 - val_loss: 75.0893 - val_root_mean_squared_error: 8.6654
Epoch 9/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 76.4266 - root_mean_squared_error: 8.7422 - val_loss: 72.8392 - val_root_mean_squared_error: 8.5346
Epoch 10/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 71.9411 - root_mean_squared_error: 8.4818 - val_loss: 71.6679 - val_root_mean_squared_error: 8.4657
Epoch 11/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 73.2373 - root_mean_squared_error: 8.5579 - val_loss: 71.2364 - val_root_mean_squared_error: 8.4402
Epoch 12/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 74.4296 - root_mean_squared_error: 8.6273 - val_loss: 70.7078 - val_root_mean_squared_error: 8.4088
Epoch 13/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 76.6296 - root_mean_squared_error: 8.7538 - val_loss: 70.1698 - val_root_mean_squared_error: 8.3767
Epoch 14/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 85.3691 - root_mean_squared_error: 9.2395 - val_loss: 70.1479 - val_root_mean_squared_error: 8.3754
Epoch 15/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 77.0577 - root_mean_squared_error: 8.7782 - val_loss: 70.4961 - val_root_mean_squared_error: 8.3962
Epoch 16/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 72.6127 - root_mean_squared_error: 8.5213 - val_loss: 70.2601 - val_root_mean_squared_error: 8.3821
Epoch 17/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 75.7514 - root_mean_squared_error: 8.7035 - val_loss: 70.2778 - val_root_mean_squared_error: 8.3832
Epoch 18/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 71.7432 - root_mean_squared_error: 8.4701 - val_loss: 70.1550 - val_root_mean_squared_error: 8.3759
Epoch 19/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 74.5853 - root_mean_squared_error: 8.6363 - val_loss: 70.2076 - val_root_mean_squared_error: 8.3790
Epoch 20/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 74.8482 - root_mean_squared_error: 8.6515 - val_loss: 70.3236 - val_root_mean_squared_error: 8.3859
Epoch 21/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 75.4317 - root_mean_squared_error: 8.6851 - val_loss: 70.1324 - val_root_mean_squared_error: 8.3745
Epoch 22/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 71.3010 - root_mean_squared_error: 8.4440 - val_loss: 69.8485 - val_root_mean_squared_error: 8.3575
Epoch 23/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 74.2239 - root_mean_squared_error: 8.6153 - val_loss: 70.0145 - val_root_mean_squared_error: 8.3675
Epoch 24/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 74.8793 - root_mean_squared_error: 8.6533 - val_loss: 70.1073 - val_root_mean_squared_error: 8.3730
Epoch 25/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 72.3588 - root_mean_squared_error: 8.5064 - val_loss: 70.2126 - val_root_mean_squared_error: 8.3793
Epoch 26/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 77.7023 - root_mean_squared_error: 8.8149 - val_loss: 70.7380 - val_root_mean_squared_error: 8.4106
Epoch 27/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 72.8444 - root_mean_squared_error: 8.5349 - val_loss: 77.1438 - val_root_mean_squared_error: 8.7832
Epoch 28/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 70.8286 - root_mean_squared_error: 8.4160 - val_loss: 69.3988 - val_root_mean_squared_error: 8.3306
Epoch 29/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 70.7211 - root_mean_squared_error: 8.4096 - val_loss: 69.0217 - val_root_mean_squared_error: 8.3079
Epoch 30/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 71.6773 - root_mean_squared_error: 8.4662 - val_loss: 68.5432 - val_root_mean_squared_error: 8.2791
Epoch 31/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 69.3673 - root_mean_squared_error: 8.3287 - val_loss: 67.5290 - val_root_mean_squared_error: 8.2176
Epoch 32/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 72.1617 - root_mean_squared_error: 8.4948 - val_loss: 68.5938 - val_root_mean_squared_error: 8.2821
Epoch 33/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 75.4861 - root_mean_squared_error: 8.6883 - val_loss: 71.9943 - val_root_mean_squared_error: 8.4849
Epoch 34/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 73.6772 - root_mean_squared_error: 8.5835 - val_loss: 69.9874 - val_root_mean_squared_error: 8.3658
Epoch 35/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 82.3775 - root_mean_squared_error: 9.0762 - val_loss: 70.1273 - val_root_mean_squared_error: 8.3742
Epoch 36/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 65.4323 - root_mean_squared_error: 8.0890 - val_loss: 67.1324 - val_root_mean_squared_error: 8.1934
Epoch 37/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 69.7735 - root_mean_squared_error: 8.3531 - val_loss: 65.3399 - val_root_mean_squared_error: 8.0833
Epoch 38/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 69.0207 - root_mean_squared_error: 8.3079 - val_loss: 65.7570 - val_root_mean_squared_error: 8.1091
Epoch 39/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 62.8255 - root_mean_squared_error: 7.9263 - val_loss: 68.2909 - val_root_mean_squared_error: 8.2638
Epoch 40/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 70.9040 - root_mean_squared_error: 8.4205 - val_loss: 65.8529 - val_root_mean_squared_error: 8.1150
Epoch 41/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 62.0918 - root_mean_squared_error: 7.8798 - val_loss: 66.4128 - val_root_mean_squared_error: 8.1494
Epoch 42/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 74.3074 - root_mean_squared_error: 8.6202 - val_loss: 66.2532 - val_root_mean_squared_error: 8.1396
Epoch 43/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 62.0876 - root_mean_squared_error: 7.8796 - val_loss: 65.1074 - val_root_mean_squared_error: 8.0689
Epoch 44/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 71.9251 - root_mean_squared_error: 8.4809 - val_loss: 65.5616 - val_root_mean_squared_error: 8.0970
Epoch 45/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 68.4073 - root_mean_squared_error: 8.2709 - val_loss: 66.1209 - val_root_mean_squared_error: 8.1315
Epoch 46/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 67.6351 - root_mean_squared_error: 8.2241 - val_loss: 70.3000 - val_root_mean_squared_error: 8.3845
Epoch 47/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 70.3669 - root_mean_squared_error: 8.3885 - val_loss: 66.4348 - val_root_mean_squared_error: 8.1508
Epoch 48/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 69.4005 - root_mean_squared_error: 8.3307 - val_loss: 69.6165 - val_root_mean_squared_error: 8.3437
Epoch 49/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 69.1151 - root_mean_squared_error: 8.3135 - val_loss: 64.8233 - val_root_mean_squared_error: 8.0513
Epoch 50/50
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 74.9829 - root_mean_squared_error: 8.6593 - val_loss: 64.0743 - val_root_mean_squared_error: 8.0046

In [20]:
new_num_cols = ['DayOfYear', 'AvgTemperture', 'Wind', 'Solar_lag1', 'Solar_lag7']
new_cat_cols=['Season', 'PressureBin']

In [21]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), new_cat_cols),
        ("num", StandardScaler(), new_num_cols)
    ]
)

model = XGBRegressor(random_state=42)

pipeline = Pipeline(steps=[
    ("preprocess", preprocessor),
    ("model", model)
])

pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_val)

print("R²:", r2_score(y_val, y_pred))
print("MAE:", mean_absolute_error(y_val, y_pred))
print("RMSE:", root_mean_squared_error(y_val, y_pred))

R²: 0.8733375485386466
MAE: 2.4015952452795832
RMSE: 2.776464009490229

In [22]:
param_grid = {
    "model__n_estimators": [100, 300, 500, 800],
    "model__learning_rate": [0.01, 0.05, 0.1],
    "model__max_depth": [2, 3, 4, 5, None],
    "model__min_child_weight": [1, 3, 5, 10],
    "model__subsample": [0.6, 0.8, 1.0],
    "model__colsample_bytree": [0.6, 0.8, 1.0],
    "model__gamma": [0, 0.1, 0.3, 1.0],
}

grid = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    scoring="neg_root_mean_squared_error",
    cv=5,               
    n_jobs=-1,         
    verbose=2
)

grid.fit(X_train, y_train)

print("Best CV RMSE:", -grid.best_score_)
print("Best params:")
for k, v in grid.best_params_.items():
    print(f"  {k}: {v}")

best_xgb_model = grid.best_estimator_

y_pred_xgb = best_xgb_model.predict(X_val)

print("Validation R²:", r2_score(y_val, y_pred_xgb))
print("Validation MAE:", mean_absolute_error(y_val, y_pred_xgb))
print("Validation RMSE:", root_mean_squared_error(y_val, y_pred_xgb))

Fitting 5 folds for each of 8640 candidates, totalling 43200 fits
Best CV RMSE: 3.838254716191686
Best params:
  model__colsample_bytree: 0.8
  model__gamma: 1.0
  model__learning_rate: 0.01
  model__max_depth: None
  model__min_child_weight: 1
  model__n_estimators: 800
  model__subsample: 0.8
Validation R²: 0.858971641571572
Validation MAE: 2.5009766742425747
Validation RMSE: 2.929687708354021

In [23]:
et = ExtraTreesRegressor(
    random_state=42,
    n_jobs=-1
)

param_grid_et = {
    "model__n_estimators": [200, 500, 800],
    "model__max_depth": [None, 5, 10, 20],
    "model__min_samples_split": [2, 5, 10],
    "model__min_samples_leaf": [1, 2, 5],
    "model__max_features": ["sqrt", "log2", 0.5, 1.0],
    "model__bootstrap": [False, True],
}

pipeline_et = Pipeline(steps=[
    ("preprocess", preprocessor),
    ("model", et)
])

grid_et = GridSearchCV(
    estimator=pipeline_et,
    param_grid=param_grid_et,
    scoring="neg_root_mean_squared_error",
    cv=5,
    n_jobs=-1,
    verbose=2
)

grid_et.fit(X_train, y_train)

print("Best CV RMSE (ExtraTrees):", -grid_et.best_score_)
print("Best params (ExtraTrees):")
for k, v in grid_et.best_params_.items():
    print(f"  {k}: {v}")

best_et_model = grid_et.best_estimator_
y_pred_et = best_et_model.predict(X_val)

print("Validation R²:", r2_score(y_val, y_pred_et))
print("Validation MAE:", mean_absolute_error(y_val, y_pred_et))
print("Validation RMSE:", root_mean_squared_error(y_val, y_pred_et))

Fitting 5 folds for each of 864 candidates, totalling 4320 fits
Best CV RMSE (ExtraTrees): 3.532075044282643
Best params (ExtraTrees):
  model__bootstrap: False
  model__max_depth: None
  model__max_features: 1.0
  model__min_samples_leaf: 1
  model__min_samples_split: 2
  model__n_estimators: 200
Validation R²: 0.8368194400979359
Validation MAE: 2.552375714162424
Validation RMSE: 3.1513911645466335

In [27]:
y_pred_xgb = best_xgb_model.predict(X_test)

print("Test R²:", r2_score(y_test, y_pred_xgb))
print("Test MAE:", mean_absolute_error(y_test, y_pred_xgb))
print("Test RMSE:", root_mean_squared_error(y_test, y_pred_xgb))

Test R²: 0.8083784749446565
Test MAE: 2.1452568348815553
Test RMSE: 3.17903080465149

In [39]:
y_pred_et = best_et_model.predict(X_test)

print("Test R²:", r2_score(y_test, y_pred_et))
print("Test MAE:", mean_absolute_error(y_test, y_pred_et))
print("Test RMSE:", root_mean_squared_error(y_test, y_pred_et))

Test R²: 0.8655570861329972
Test MAE: 1.780653375647875
Test RMSE: 2.6628183948906465

In [30]:
joblib.dump(best_xgb_model, 'models/best_xgb_model.joblib')
joblib.dump(best_et_model, 'models/best_et_model.joblib')

['models/best_et_model.joblib']